-- Per-item production status, purchase-order lines linked to inventory, automatic reorder,
-- secondary display currency and phone region settings.

-- Payment reminders get their own alert type (rows are moved in the next migration: a new enum
-- value cannot be used in the transaction that adds it). REORDER_REMINDER is kept for stock reorders.
ALTER TYPE "AlertType" ADD VALUE 'PAYMENT_REMINDER';

-- ── Per-item production status ─────────────────────────────────────────────
ALTER TABLE "OrderItem" ADD COLUMN "status" "OrderStatus" NOT NULL DEFAULT 'NEW',
ADD COLUMN "statusUpdatedAt" TIMESTAMP(3);

-- Every existing item starts at its order's current status
UPDATE "OrderItem" oi
SET "status" = o."status", "statusUpdatedAt" = o."updatedAt"
FROM "Order" o
WHERE oi."orderId" = o."id";

CREATE INDEX "OrderItem_status_idx" ON "OrderItem"("status");
CREATE INDEX "OrderItem_assignedTailorId_status_idx" ON "OrderItem"("assignedTailorId", "status");

ALTER TABLE "OrderHistory" ADD COLUMN "orderItemId" TEXT;
CREATE INDEX "OrderHistory_orderItemId_idx" ON "OrderHistory"("orderItemId");
ALTER TABLE "OrderHistory" ADD CONSTRAINT "OrderHistory_orderItemId_fkey" FOREIGN KEY ("orderItemId") REFERENCES "OrderItem"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ── Purchase-order lines linked to inventory ───────────────────────────────
ALTER TABLE "POItem" ADD COLUMN "accessoryInventoryId" TEXT,
ADD COLUMN "clothInventoryId" TEXT;

-- Link existing lines whose name matches exactly one item of their type (case/space-insensitive).
-- Lines with no or several matches stay unlinked and are linked when first received.
UPDATE "POItem" p
SET "clothInventoryId" = c."id"
FROM "ClothInventory" c
WHERE p."itemType" = 'CLOTH'
  AND lower(btrim(c."name")) = lower(btrim(p."itemName"))
  AND (SELECT count(*) FROM "ClothInventory" c2 WHERE lower(btrim(c2."name")) = lower(btrim(p."itemName"))) = 1;

UPDATE "POItem" p
SET "accessoryInventoryId" = a."id"
FROM "AccessoryInventory" a
WHERE p."itemType" = 'ACCESSORY'
  AND lower(btrim(a."name")) = lower(btrim(p."itemName"))
  AND (SELECT count(*) FROM "AccessoryInventory" a2 WHERE lower(btrim(a2."name")) = lower(btrim(p."itemName"))) = 1;

CREATE INDEX "POItem_clothInventoryId_idx" ON "POItem"("clothInventoryId");
CREATE INDEX "POItem_accessoryInventoryId_idx" ON "POItem"("accessoryInventoryId");
ALTER TABLE "POItem" ADD CONSTRAINT "POItem_clothInventoryId_fkey" FOREIGN KEY ("clothInventoryId") REFERENCES "ClothInventory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "POItem" ADD CONSTRAINT "POItem_accessoryInventoryId_fkey" FOREIGN KEY ("accessoryInventoryId") REFERENCES "AccessoryInventory"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "PurchaseOrder" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- ── Reorder quantities ─────────────────────────────────────────────────────
ALTER TABLE "ClothInventory" ADD COLUMN "reorderQuantity" DOUBLE PRECISION;
ALTER TABLE "AccessoryInventory" ADD COLUMN "reorderQuantity" INTEGER;

-- ── Settings ───────────────────────────────────────────────────────────────
ALTER TABLE "BusinessSettings" ADD COLUMN "autoReorderEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "exchangeRate" DOUBLE PRECISION,
ADD COLUMN "exchangeRateUpdatedAt" TIMESTAMP(3),
ADD COLUMN "phoneRegion" TEXT NOT NULL DEFAULT 'IN',
ADD COLUMN "secondaryCurrencyCode" TEXT,
ADD COLUMN "showSecondaryOnInvoice" BOOLEAN NOT NULL DEFAULT false;

-- The calling code setting becomes an ISO country (needed to validate national numbers).
-- Shared calling codes map to their main country (1 → US, 7 → RU, 44 → GB); anything unknown → IN.
UPDATE "BusinessSettings" SET "phoneRegion" = CASE "phoneCountryCode"
  WHEN '91' THEN 'IN' WHEN '1' THEN 'US' WHEN '44' THEN 'GB' WHEN '971' THEN 'AE' WHEN '966' THEN 'SA'
  WHEN '974' THEN 'QA' WHEN '968' THEN 'OM' WHEN '965' THEN 'KW' WHEN '973' THEN 'BH' WHEN '61' THEN 'AU'
  WHEN '64' THEN 'NZ' WHEN '65' THEN 'SG' WHEN '60' THEN 'MY' WHEN '852' THEN 'HK' WHEN '86' THEN 'CN'
  WHEN '81' THEN 'JP' WHEN '82' THEN 'KR' WHEN '92' THEN 'PK' WHEN '880' THEN 'BD' WHEN '94' THEN 'LK'
  WHEN '977' THEN 'NP' WHEN '27' THEN 'ZA' WHEN '254' THEN 'KE' WHEN '234' THEN 'NG' WHEN '49' THEN 'DE'
  WHEN '33' THEN 'FR' WHEN '39' THEN 'IT' WHEN '34' THEN 'ES' WHEN '31' THEN 'NL' WHEN '353' THEN 'IE'
  WHEN '41' THEN 'CH' WHEN '46' THEN 'SE' WHEN '47' THEN 'NO' WHEN '45' THEN 'DK' WHEN '7' THEN 'RU'
  WHEN '55' THEN 'BR' WHEN '52' THEN 'MX' WHEN '90' THEN 'TR' WHEN '20' THEN 'EG'
  ELSE 'IN' END;

ALTER TABLE "BusinessSettings" DROP COLUMN "phoneCountryCode";
