/**
 * FEATURETRACE: Automatic reorder check (finishing inventory: fabric + accessories)
 *
 *   computeReorderPositions / computeReorderNeeds — pure: stock position and suggested quantity per item.
 *     available = currentStock − reserved
 *     onOrder   = Σ (ordered − received) over linked lines on open POs (PENDING_APPROVAL, PENDING, APPROVED, PARTIAL)
 *     awaiting  = the part of onOrder on POs not yet approved (PENDING_APPROVAL, PENDING)
 *     needs a reorder when available + (onOrder − awaiting) ≤ minimum — the alert stays until the PO is approved
 *     quantity  = (reorderQuantity ?? max(0, 2 × minimum − available − approved on order)) − awaiting,
 *                 rounded up to whole meters / units; 0 means only an approval is outstanding
 *     price     = current SupplierPrice for the fabric from the item's supplier, otherwise the item's own price
 *
 *   runReorderCheck — DB runner, one at a time (transaction-scoped advisory lock; skips when busy):
 *     raises / updates / resolves REORDER_REMINDER alerts per item (relatedType 'cloth' | 'accessory');
 *     when BusinessSettings.autoReorderEnabled, drafts one PENDING_APPROVAL PO per supplier
 *     (autoGenerated) or appends to the existing draft — an item already on the draft is never added twice.
 *
 *   Triggers: lib/generate-alerts.ts, after() in POST /api/orders, order-item fabric changes, inventory
 *   stock adjust/edit routes, and POST /api/inventory/reorder/run.
 */

import type { AlertSeverity } from '@prisma/client'
import { prisma } from '@/lib/db'
import type { TransactionClient } from '@/lib/prisma-client'
import { audit } from '@/lib/audit'
import { getAppSettings } from '@/lib/settings'
import { formatDate } from '@/lib/locale'
import { multiplyMoney, subtractMoney, sumMoney } from '@/lib/money'
import { roundMeters } from '@/lib/stock'
import {
  OPEN_PO_STATUSES,
  PO_LINE_UNIT,
  UNAPPROVED_PO_STATUSES,
  accessoryLineName,
  clothLineName,
  nextPoNumber,
  type POItemType,
} from '@/lib/purchase-order-items'

/** pg advisory-lock key reserved for the reorder check (any constant unique to this job). */
export const REORDER_LOCK_KEY = 72_410_031

export type ReorderKind = 'cloth' | 'accessory'

export type ReorderTrigger =
  | 'manual'
  | 'alerts'
  | 'order_created'
  | 'order_item_fabric_changed'
  | 'stock_adjusted'
  | 'inventory_edited'
  | 'purchase_order_changed'

const TRIGGER_LABELS: Record<ReorderTrigger, string> = {
  purchase_order_changed: 'purchase order change',
  manual: 'manual check',
  alerts: 'scheduled alert check',
  order_created: 'new order',
  order_item_fabric_changed: 'fabric change',
  stock_adjusted: 'stock adjustment',
  inventory_edited: 'inventory edit',
}

export interface ReorderItem {
  kind: ReorderKind
  id: string
  sku: string
  name: string
  /** PO line name derived from the item (lib/purchase-order-items) */
  lineName: string
  currentStock: number
  reserved: number
  minimum: number
  reorderQuantity: number | null
  /** Only an active supplier counts; inactive or missing → null */
  supplierId: string | null
  supplierName: string | null
  /** pricePerMeter (cloth) or pricePerUnit (accessory) */
  itemPrice: number
}

export interface OpenPOLine {
  status: string
  clothInventoryId: string | null
  accessoryInventoryId: string | null
  orderedQuantity: number
  receivedQuantity: number
}

export interface SupplierPriceRow {
  supplierId: string
  clothInventoryId: string
  pricePerMeter: number
  effectiveFrom: Date
  effectiveTo: Date | null
  active: boolean
}

export interface ReorderInput {
  items: ReorderItem[]
  openLines: OpenPOLine[]
  supplierPrices?: SupplierPriceRow[]
  now?: Date
}

export interface ReorderPosition {
  kind: ReorderKind
  id: string
  sku: string
  name: string
  lineName: string
  itemType: POItemType
  unit: 'meters' | 'pieces'
  available: number
  onOrder: number
  /** The part of onOrder on purchase orders not yet approved */
  awaitingApproval: number
  minimum: number
  reorderQuantity: number | null
  /** Needs a reorder alert: an approval still counts as not reordered */
  needsReorder: boolean
  /** Quantity still to put on a PO (whole meters / units); 0 when not needed or when POs awaiting approval cover it */
  suggestedQuantity: number
  supplierId: string | null
  supplierName: string | null
  unitPrice: number
  priceSource: 'supplier' | 'item'
  severity: AlertSeverity
}

export type ReorderNeed = ReorderPosition & { needsReorder: true }

export const itemKey = (kind: ReorderKind, id: string) => `${kind}:${id}`

const round3 = roundMeters
const EPSILON = 1e-9

/** Current price for a fabric from a supplier: active, effective now, latest effectiveFrom wins. */
export function pickSupplierPrice(
  prices: SupplierPriceRow[],
  clothInventoryId: string,
  supplierId: string | null,
  now: Date = new Date()
): number | null {
  if (!supplierId) return null
  let best: SupplierPriceRow | null = null
  for (const p of prices) {
    if (!p.active || p.clothInventoryId !== clothInventoryId || p.supplierId !== supplierId) continue
    if (p.effectiveFrom.getTime() > now.getTime()) continue
    if (p.effectiveTo && p.effectiveTo.getTime() < now.getTime()) continue
    if (!best || p.effectiveFrom.getTime() > best.effectiveFrom.getTime()) best = p
  }
  return best ? best.pricePerMeter : null
}

/** Outstanding quantity per item on linked lines of POs in one of `statuses`. */
function outstandingByItem(lines: OpenPOLine[], statuses: readonly string[]): Map<string, number> {
  const wanted = new Set<string>(statuses)
  const totals = new Map<string, number>()
  for (const line of lines) {
    if (!wanted.has(line.status)) continue
    const key = line.clothInventoryId
      ? itemKey('cloth', line.clothInventoryId)
      : line.accessoryInventoryId
        ? itemKey('accessory', line.accessoryInventoryId)
        : null
    if (!key) continue
    const outstanding = Math.max(0, line.orderedQuantity - line.receivedQuantity)
    totals.set(key, round3((totals.get(key) ?? 0) + outstanding))
  }
  return totals
}

/** Outstanding quantity per item across open POs (linked lines only). */
export function computeOnOrder(lines: OpenPOLine[]): Map<string, number> {
  return outstandingByItem(lines, OPEN_PO_STATUSES)
}

/** The part of computeOnOrder on purchase orders not yet approved. */
export function computeAwaitingApproval(lines: OpenPOLine[]): Map<string, number> {
  return outstandingByItem(lines, UNAPPROVED_PO_STATUSES)
}

/** Severity by physical shortfall: out of stock → CRITICAL, at or below half the minimum → HIGH, else MEDIUM. */
export function reorderSeverity(available: number, minimum: number): AlertSeverity {
  if (available <= 0) return 'CRITICAL'
  if (available <= minimum * 0.5) return 'HIGH'
  return 'MEDIUM'
}

/** Whole meters (cloth) / units (accessories), always rounded up. */
function wholeQuantity(quantity: number): number {
  return Math.max(0, Math.ceil(round3(quantity) - EPSILON))
}

/**
 * The reorder rule for one item. `onOrder` is everything outstanding on open POs; `awaitingApproval`
 * is the part of it on POs not yet approved.
 *   needed   when available + approved on-order ≤ minimum — a draft doesn't settle it until approved
 *   quantity = (reorderQuantity, else enough to reach twice the minimum after approved on-order)
 *              − what already awaits approval, rounded up to a whole meter / unit; 0 = only an approval is due
 */
export function reorderSuggestion(p: {
  available: number
  onOrder: number
  awaitingApproval?: number
  minimum: number
  reorderQuantity: number | null
}): { needsReorder: boolean; quantity: number } {
  const pending = Math.min(p.awaitingApproval ?? 0, p.onOrder)
  const approved = p.onOrder - pending
  const needsReorder = round3(p.available + approved) <= p.minimum + EPSILON
  const reorderQuantity = p.reorderQuantity && p.reorderQuantity > 0 ? p.reorderQuantity : null
  const target = reorderQuantity ?? Math.max(0, 2 * p.minimum - p.available - approved)
  return { needsReorder, quantity: needsReorder ? wholeQuantity(Math.max(0, target - pending)) : 0 }
}

/**
 * Stock position and suggested order for every item.
 * `priceSupplierId` prices fabric from that supplier instead of each item's own supplier
 * (the PO picker passes the PO's supplier).
 */
export function computeReorderPositions(
  input: ReorderInput,
  opts: { priceSupplierId?: string | null } = {}
): ReorderPosition[] {
  const now = input.now ?? new Date()
  const onOrderMap = computeOnOrder(input.openLines)
  const awaitingMap = computeAwaitingApproval(input.openLines)
  const prices = input.supplierPrices ?? []

  return input.items.map((item) => {
    const isCloth = item.kind === 'cloth'
    const available = isCloth ? round3(item.currentStock - item.reserved) : item.currentStock - item.reserved
    const onOrder = onOrderMap.get(itemKey(item.kind, item.id)) ?? 0
    const awaitingApproval = awaitingMap.get(itemKey(item.kind, item.id)) ?? 0
    const reorderQuantity = item.reorderQuantity && item.reorderQuantity > 0 ? item.reorderQuantity : null
    const { needsReorder, quantity: suggestedQuantity } = reorderSuggestion({
      available,
      onOrder,
      awaitingApproval,
      minimum: item.minimum,
      reorderQuantity,
    })

    const supplierPrice = isCloth
      ? pickSupplierPrice(prices, item.id, opts.priceSupplierId ?? item.supplierId, now)
      : null

    return {
      kind: item.kind,
      id: item.id,
      sku: item.sku,
      name: item.name,
      lineName: item.lineName,
      itemType: isCloth ? 'CLOTH' : 'ACCESSORY',
      unit: isCloth ? PO_LINE_UNIT.CLOTH : PO_LINE_UNIT.ACCESSORY,
      available,
      onOrder,
      minimum: item.minimum,
      reorderQuantity,
      awaitingApproval,
      needsReorder,
      suggestedQuantity,
      supplierId: item.supplierId,
      supplierName: item.supplierName,
      unitPrice: supplierPrice ?? item.itemPrice,
      priceSource: supplierPrice !== null ? 'supplier' : 'item',
      severity: reorderSeverity(available, item.minimum),
    }
  })
}

/**
 * Items that need a reorder (each keeps an alert). suggestedQuantity is 0 when purchase orders awaiting
 * approval already cover the item — then only the approval is outstanding and nothing more is drafted.
 */
export function computeReorderNeeds(input: ReorderInput): ReorderNeed[] {
  return computeReorderPositions(input).filter((p): p is ReorderNeed => p.needsReorder)
}

// ── DB runner ────────────────────────────────────────────────────────────────

type ReorderReader = Pick<TransactionClient, 'clothInventory' | 'accessoryInventory' | 'pOItem' | 'supplierPrice'>

/** Load active items, open PO lines and current supplier prices. */
export async function loadReorderInput(client: ReorderReader, now: Date = new Date()): Promise<ReorderInput> {
  const cloth = await client.clothInventory.findMany({
    where: { active: true },
    select: {
      id: true,
      sku: true,
      name: true,
      brand: true,
      color: true,
      currentStock: true,
      reserved: true,
      minimumStockMeters: true,
      reorderQuantity: true,
      pricePerMeter: true,
      supplierId: true,
      supplierRel: { select: { id: true, name: true, active: true } },
    },
    orderBy: { name: 'asc' },
  })
  const accessories = await client.accessoryInventory.findMany({
    where: { active: true },
    select: {
      id: true,
      sku: true,
      name: true,
      color: true,
      currentStock: true,
      reserved: true,
      minimumStockUnits: true,
      reorderQuantity: true,
      pricePerUnit: true,
      supplierId: true,
      supplierRel: { select: { id: true, name: true, active: true } },
    },
    orderBy: { name: 'asc' },
  })
  const lines = await client.pOItem.findMany({
    where: {
      purchaseOrder: { active: true, status: { in: [...OPEN_PO_STATUSES] } },
      OR: [{ clothInventoryId: { not: null } }, { accessoryInventoryId: { not: null } }],
    },
    select: {
      clothInventoryId: true,
      accessoryInventoryId: true,
      orderedQuantity: true,
      receivedQuantity: true,
      purchaseOrder: { select: { status: true } },
    },
  })
  const supplierPrices = await client.supplierPrice.findMany({
    where: {
      active: true,
      effectiveFrom: { lte: now },
      OR: [{ effectiveTo: null }, { effectiveTo: { gte: now } }],
    },
    select: {
      supplierId: true,
      clothInventoryId: true,
      pricePerMeter: true,
      effectiveFrom: true,
      effectiveTo: true,
      active: true,
    },
  })

  const activeSupplier = (rel: { id: string; name: string; active: boolean } | null) =>
    rel && rel.active ? rel : null

  const items: ReorderItem[] = [
    ...(cloth ?? []).map((c) => {
      const supplier = activeSupplier(c.supplierRel)
      return {
        kind: 'cloth' as const,
        id: c.id,
        sku: c.sku,
        name: c.name,
        lineName: clothLineName(c),
        currentStock: c.currentStock,
        reserved: c.reserved,
        minimum: c.minimumStockMeters,
        reorderQuantity: c.reorderQuantity,
        supplierId: supplier?.id ?? null,
        supplierName: supplier?.name ?? null,
        itemPrice: c.pricePerMeter,
      }
    }),
    ...(accessories ?? []).map((a) => {
      const supplier = activeSupplier(a.supplierRel)
      return {
        kind: 'accessory' as const,
        id: a.id,
        sku: a.sku,
        name: a.name,
        lineName: accessoryLineName(a),
        currentStock: a.currentStock,
        reserved: a.reserved,
        minimum: a.minimumStockUnits,
        reorderQuantity: a.reorderQuantity,
        supplierId: supplier?.id ?? null,
        supplierName: supplier?.name ?? null,
        itemPrice: a.pricePerUnit,
      }
    }),
  ]

  return {
    items,
    openLines: (lines ?? []).map((l) => ({
      status: l.purchaseOrder.status,
      clothInventoryId: l.clothInventoryId,
      accessoryInventoryId: l.accessoryInventoryId,
      orderedQuantity: l.orderedQuantity,
      receivedQuantity: l.receivedQuantity,
    })),
    supplierPrices: supplierPrices ?? [],
    now,
  }
}

export interface ReorderRunPurchaseOrder {
  id: string
  poNumber: string
  supplierId: string
  created: boolean
  linesAdded: number
}

export interface ReorderRunResult {
  status: 'completed' | 'skipped'
  trigger: ReorderTrigger
  autoReorderEnabled: boolean
  needs: number
  alertsCreated: number
  alertsUpdated: number
  alertsResolved: number
  purchaseOrders: ReorderRunPurchaseOrder[]
}

const fmtQty = (n: number) => String(round3(n))

function alertText(need: ReorderNeed, draftPoNumber: string | undefined) {
  const unit = need.unit
  const approved = round3(need.onOrder - need.awaitingApproval)
  const supplier = need.supplierName ? ` from ${need.supplierName}.` : ' — no supplier linked.'
  const action =
    need.suggestedQuantity > 0
      ? `. Reorder ${fmtQty(need.suggestedQuantity)} ${unit}${supplier}` +
        (draftPoNumber ? ` On draft purchase order ${draftPoNumber}, awaiting approval.` : '')
      : draftPoNumber
        ? `. Approve draft purchase order ${draftPoNumber} to confirm the reorder.`
        : '. Approve the purchase order awaiting approval to confirm the reorder.'
  const parts = [
    `${need.lineName}: available ${fmtQty(need.available)} ${unit}, minimum ${fmtQty(need.minimum)} ${unit}`,
    approved > 0 ? `, ${fmtQty(approved)} ${unit} already on order` : '',
    need.awaitingApproval > 0 ? `, ${fmtQty(need.awaitingApproval)} ${unit} awaiting approval` : '',
    action,
  ]
  return { title: `Reorder: ${need.name}`, message: parts.join('') }
}

/**
 * Run the reorder check once. Returns status 'skipped' when another run holds the lock.
 * Throws on database errors — background callers use runReorderCheckQuietly().
 */
export async function runReorderCheck(opts: {
  trigger: ReorderTrigger
  userId?: string | null
  now?: Date
}): Promise<ReorderRunResult> {
  const now = opts.now ?? new Date()
  const settings = await getAppSettings() // also primes the locale for the PO note date
  const autoReorderEnabled = settings.autoReorderEnabled

  const empty: ReorderRunResult = {
    status: 'skipped',
    trigger: opts.trigger,
    autoReorderEnabled,
    needs: 0,
    alertsCreated: 0,
    alertsUpdated: 0,
    alertsResolved: 0,
    purchaseOrders: [],
  }
  const auditLines = new Map<string, Array<{ kind: ReorderKind; itemId: string; quantity: number }>>()

  const outcome = await prisma.$transaction(
    async (tx: TransactionClient) => {
      const lock = await tx.$queryRaw<Array<{ locked: boolean }>>`
        SELECT pg_try_advisory_xact_lock(${REORDER_LOCK_KEY}::bigint) AS "locked"
      `
      if (!lock?.[0]?.locked) return null

      const result: ReorderRunResult = { ...empty, status: 'completed', purchaseOrders: [] }
      const needs = computeReorderNeeds(await loadReorderInput(tx, now))
      result.needs = needs.length

      // ── Draft purchase orders (one open auto-draft per supplier) ──────────────
      const draftPoByItem = new Map<string, string>()
      if (autoReorderEnabled) {
        const bySupplier = new Map<string, ReorderNeed[]>()
        for (const need of needs) {
          if (!need.supplierId) continue
          bySupplier.set(need.supplierId, [...(bySupplier.get(need.supplierId) ?? []), need])
        }

        for (const [supplierId, group] of bySupplier) {
          const draft = await tx.purchaseOrder.findFirst({
            where: { supplierId, autoGenerated: true, status: 'PENDING_APPROVAL', active: true },
            include: { items: true },
            orderBy: { createdAt: 'desc' },
          })

          const onDraft = new Set<string>()
          for (const line of draft?.items ?? []) {
            if (line.clothInventoryId) onDraft.add(itemKey('cloth', line.clothInventoryId))
            if (line.accessoryInventoryId) onDraft.add(itemKey('accessory', line.accessoryInventoryId))
          }

          // Items whose shortfall is already covered by POs awaiting approval only need that approval
          const toAdd = group.filter((need) => need.suggestedQuantity > 0 && !onDraft.has(itemKey(need.kind, need.id)))
          if (draft) {
            for (const need of group) {
              if (onDraft.has(itemKey(need.kind, need.id))) draftPoByItem.set(itemKey(need.kind, need.id), draft.poNumber)
            }
          }
          if (toAdd.length === 0) continue

          const lines = toAdd.map((need) => ({
            itemName: need.lineName,
            itemType: need.itemType,
            orderedQuantity: need.suggestedQuantity,
            unit: need.unit,
            pricePerUnit: need.unitPrice,
            totalPrice: multiplyMoney(need.unitPrice, need.suggestedQuantity),
            clothInventoryId: need.kind === 'cloth' ? need.id : null,
            accessoryInventoryId: need.kind === 'accessory' ? need.id : null,
          }))

          let po: { id: string; poNumber: string }
          if (draft) {
            for (const line of lines) {
              await tx.pOItem.create({ data: { ...line, purchaseOrderId: draft.id } })
            }
            const totalAmount = sumMoney([...draft.items.map((i) => i.totalPrice), ...lines.map((l) => l.totalPrice)])
            await tx.purchaseOrder.update({
              where: { id: draft.id },
              data: { totalAmount, subTotal: totalAmount, balanceAmount: subtractMoney(totalAmount, draft.paidAmount) },
            })
            po = draft
          } else {
            const totalAmount = sumMoney(lines.map((l) => l.totalPrice))
            po = await tx.purchaseOrder.create({
              data: {
                poNumber: await nextPoNumber(tx, now),
                supplierId,
                status: 'PENDING_APPROVAL',
                autoGenerated: true,
                totalAmount,
                subTotal: totalAmount,
                balanceAmount: totalAmount,
                notes: `Auto-generated reorder (${TRIGGER_LABELS[opts.trigger]}) on ${formatDate(now)}. Review quantities and prices, then approve.`,
                items: { create: lines },
              },
              select: { id: true, poNumber: true },
            })
          }

          for (const need of toAdd) draftPoByItem.set(itemKey(need.kind, need.id), po.poNumber)
          result.purchaseOrders.push({
            id: po.id,
            poNumber: po.poNumber,
            supplierId,
            created: !draft,
            linesAdded: lines.length,
          })
          auditLines.set(
            po.id,
            toAdd.map((need) => ({ kind: need.kind, itemId: need.id, quantity: need.suggestedQuantity }))
          )
        }
      }

      // ── Alerts: one REORDER_REMINDER per item ────────────────────────────────
      // Unique key [relatedId, relatedType, type, isDismissed]: at most one open and one dismissed row per
      // item. A dismissed alert still inside its snooze window is respected; an expired one is re-raised in
      // place instead of creating a second row.
      const existing = await tx.alert.findMany({
        where: { type: 'REORDER_REMINDER', relatedType: { in: ['cloth', 'accessory'] } },
      })
      const openAlerts = new Map<string, (typeof existing)[number]>()
      const dismissedAlerts = new Map<string, (typeof existing)[number]>()
      for (const alert of existing ?? []) {
        if (!alert.relatedId || !alert.relatedType) continue
        const key = `${alert.relatedType}:${alert.relatedId}`
        ;(alert.isDismissed ? dismissedAlerts : openAlerts).set(key, alert)
      }

      const needKeys = new Set<string>()
      for (const need of needs) {
        const key = itemKey(need.kind, need.id)
        needKeys.add(key)
        const { title, message } = alertText(need, draftPoByItem.get(key))
        const open = openAlerts.get(key)
        const dismissed = dismissedAlerts.get(key)

        if (open) {
          if (open.title !== title || open.message !== message || open.severity !== need.severity) {
            await tx.alert.update({ where: { id: open.id }, data: { title, message, severity: need.severity } })
            result.alertsUpdated++
          }
        } else if (dismissed) {
          const snoozed = !dismissed.dismissedUntil || dismissed.dismissedUntil.getTime() > now.getTime()
          if (!snoozed) {
            await tx.alert.update({
              where: { id: dismissed.id },
              data: { title, message, severity: need.severity, isDismissed: false, dismissedUntil: null, isRead: false },
            })
            result.alertsCreated++
          }
        } else {
          await tx.alert.create({
            data: { type: 'REORDER_REMINDER', severity: need.severity, title, message, relatedId: need.id, relatedType: need.kind },
          })
          result.alertsCreated++
        }
      }

      const resolvedIds = (existing ?? [])
        .filter((alert) => !needKeys.has(`${alert.relatedType}:${alert.relatedId}`))
        .map((alert) => alert.id)
      if (resolvedIds.length > 0) {
        const deleted = await tx.alert.deleteMany({ where: { id: { in: resolvedIds } } })
        result.alertsResolved = deleted?.count ?? resolvedIds.length
      }

      return result
    },
    { maxWait: 10_000, timeout: 60_000 }
  )

  if (!outcome) return empty

  for (const po of outcome.purchaseOrders) {
    await audit({
      userId: opts.userId ?? null,
      action: po.created ? 'PURCHASE_ORDER_AUTO_CREATED' : 'PURCHASE_ORDER_AUTO_APPENDED',
      entityType: 'PurchaseOrder',
      entityId: po.id,
      details: {
        poNumber: po.poNumber,
        supplierId: po.supplierId,
        trigger: opts.trigger,
        lines: auditLines.get(po.id) ?? [],
      },
    })
  }
  return outcome
}

/** For after() callbacks: never throws, logs failures. */
export async function runReorderCheckQuietly(opts: { trigger: ReorderTrigger; userId?: string | null }): Promise<void> {
  try {
    await runReorderCheck(opts)
  } catch (error) {
    console.error(`Reorder check (${opts.trigger}) failed:`, error)
  }
}
